service: take-home-assessment

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  timeout: 30
  lambdaHashingVersion: 20201221

functions:
  get_all_orders:
    handler: handler.get_all_orders
    events:
      - httpApi:
          path: /orders
          method: get

  get_order_details:
    handler: handler.get_order_details
    events:
      - httpApi:
          path: /order/{id}
          method: get

  create_service:
    handler: handler.create_service
    events:
      - http:
          path: /service
          method: post

  create_order:
    handler: handler.create_order
    events:
      - http:
          path: /order
          method: post

  update_order:
    handler: handler.update_order
    events:
      - http:
          path: /order/{id}
          method: patch

  delete_order:
    handler: handler.delete_order
    events:
      - http:
          path: /order/{id}
          method: delete

  get_orders_over_period:
    handler: handler.get_orders_over_period
    events:
      - http:
          path: /orders/filter/{period}
          method: get
